//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellen_Conversion_M_1.WebPagesForDatabase
{


    public partial class CreateAvailability
    {
    }
}
